name: pages build and deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './src'  # Ajusta si tu index.html está dentro de /src
      - uses: actions/deploy-pages@v2
